CREATE TABLE IF NOT EXISTS user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    mobile VARCHAR(15) NOT NULL UNIQUE,
    otp VARCHAR(6),
    verified BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS worker (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    skill VARCHAR(100),
    mobile VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS booking (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT,
    worker_id BIGINT,
    status VARCHAR(50)
);
